<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\Create\" />
    <Folder Include="DTOs\Read\" />
    <Folder Include="DTOs\Update\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Helpers\" />
    <Folder Include="Services\" />
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>
